apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kapp.k14s.io/identity: v1;monitoring/apps/Deployment/clickhouse-sql-exporter;apps/v1
    kapp.k14s.io/original: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"labels":{"app":"clickhouse-sql-exporter","kapp.k14s.io/app":"1615901689600532758","kapp.k14s.io/association":"v1.6f2299100a7c0d68501775a7e52bf4b7"},"name":"clickhouse-sql-exporter","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"clickhouse-sql-exporter","kapp.k14s.io/app":"1615901689600532758"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"clickhouse-sql-exporter","kapp.k14s.io/app":"1615901689600532758","kapp.k14s.io/association":"v1.6f2299100a7c0d68501775a7e52bf4b7"}},"spec":{"containers":[{"args":["-config.file","/config/sql_exporter.yml"],"image":"eu.gcr.io/xite-cms/clickhouse-sql-exporter:5.13.0","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":2,"httpGet":{"path":"/","port":9399,"scheme":"HTTP"},"initialDelaySeconds":40,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"clickhouse-sql-exporter","readinessProbe":{"failureThreshold":2,"httpGet":{"path":"/","port":9399,"scheme":"HTTP"},"initialDelaySeconds":40,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"volumeMounts":[{"mountPath":"/config","name":"clickhouse-sql-exporter-configmap"}]}],"volumes":[{"configMap":{"defaultMode":420,"name":"clickhouse-sql-exporter-configmap"},"name":"clickhouse-sql-exporter-configmap"}]}}}}'
    kapp.k14s.io/original-diff-md5: d94d9140e5786f49a156b9e1a02220cd
  creationTimestamp: "2021-03-16T13:34:50Z"
  generation: 19
  labels:
    app: clickhouse-sql-exporter
    kapp.k14s.io/app: "1615901689600532758"
    kapp.k14s.io/association: v1.6f2299100a7c0d68501775a7e52bf4b7
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kapp.k14s.io/identity: {}
          f:kapp.k14s.io/original: {}
          f:kapp.k14s.io/original-diff-md5: {}
        f:labels:
          .: {}
          f:app: {}
          f:kapp.k14s.io/app: {}
          f:kapp.k14s.io/association: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:kapp.k14s.io/app: {}
              f:kapp.k14s.io/association: {}
          f:spec:
            f:containers:
              k:{"name":"clickhouse-sql-exporter"}:
                .: {}
                f:args: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/config"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"clickhouse-sql-exporter-configmap"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
    manager: kapp
    operation: Update
    time: "2021-06-29T14:00:03Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-01T13:11:29Z"
  name: clickhouse-sql-exporter
  namespace: monitoring
  resourceVersion: "675573149"
  uid: c8e6e9c1-c1a6-4760-95c8-aa850dea6a42
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clickhouse-sql-exporter
      kapp.k14s.io/app: "1615901689600532758"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clickhouse-sql-exporter
        kapp.k14s.io/app: "1615901689600532758"
        kapp.k14s.io/association: v1.6f2299100a7c0d68501775a7e52bf4b7
    spec:
      containers:
      - args:
        - -config.file
        - /config/sql_exporter.yml
        image: eu.gcr.io/xite-cms/clickhouse-sql-exporter:5.13.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 9399
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: clickhouse-sql-exporter
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 9399
            scheme: HTTP
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: clickhouse-sql-exporter-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: clickhouse-sql-exporter-configmap
        name: clickhouse-sql-exporter-configmap
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-16T13:34:50Z"
    lastUpdateTime: "2021-06-29T14:00:04Z"
    message: ReplicaSet "clickhouse-sql-exporter-57b75c659" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-12-01T13:11:29Z"
    lastUpdateTime: "2021-12-01T13:11:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
